# Generated by Django 4.1 on 2022-12-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
